-- Profile extensions for User
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio          TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url   VARCHAR(1000);
ALTER TABLE users ADD COLUMN IF NOT EXISTS language     VARCHAR(10) NOT NULL DEFAULT 'RU';
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_code VARCHAR(20) UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referred_by_id BIGINT REFERENCES users(id);